version: "2"

services:
  postgres:
    image: postgres:11.4
    volumes:
      - "./data/postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: opensanctions
      POSTGRES_PASSWORD: opensanctions

  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
        - 9633:8081
    links:
        - postgres
    depends_on:
        - postgres
    environment:
      DATABASE_URL: postgres://opensanctions:opensanctions@postgres:5432/opensanctions?sslmode=disable

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis-data:/data

  ui:
    build: .
    command: gunicorn -t 900 -w 8 -b 0.0.0.0:8001 --log-level info --log-file - memorious.ui.views:app
    links:
      - redis
      - postgres
    volumes:
      - "./data/data:/data"
      - "./opensanctions:/opensanctions/opensanctions"
    tmpfs:
      - "/tmp"
    ports:
      - "8001:8001"
    environment:
      MEMORIOUS_DATASTORE_URI: postgresql://opensanctions:opensanctions@postgres/opensanctions
      REDIS_URL: redis://redis:6379/0
  
  worker:
    build: .
    command: memorious process
    links:
      - postgres
      - redis
    volumes:
      - "./data/data:/data"
      - "./opensanctions:/opensanctions/opensanctions"
    tmpfs:
      - "/tmp"
    environment:
      MEMORIOUS_DATASTORE_URI: postgresql://opensanctions:opensanctions@postgres/opensanctions
      REDIS_URL: redis://redis:6379/0
      FTM_STORE_URI: postgresql://opensanctions:opensanctions@postgres/opensanctions
      WORKER_THREADS: 10
