name: coe_assembly
description: "[OSANC] Council of Europe Parliamentary Assembly"
schedule: never
pipeline:
  init:
    method: opensanctions.crawlers.coe_assembly:parse
    handle:
      page: fetch
aggregator:
  method: ftm_load_aleph
