name: eu_eeas_sanctions
description: "[OSANC] EEAS Entities Subject to EU Financial Sanctions"
schedule: never
pipeline:
  init:
    method: seed
    params:
      url: "https://data.europa.eu/euodp/es/data/dataset/consolidated-list-of-persons-groups-and-entities-subject-to-eu-financial-sanctions"
    handle:
      pass: fetch
  fetch:
    method: fetch
    handle:
      pass: get_csv_url
  get_csv_url:
    method: opensanctions.crawlers.eu_eeas_sanctions:get_csv_url
    handle:
      pass: fetch_csv
  fetch_csv:
    method: fetch
    handle:
      pass: parse
  parse:
    method: opensanctions.crawlers.eu_eeas_sanctions:eeas_parse
    handle:
      pass: download
  download:
    method: fetch
    handle:
      pass: emit_doc
  emit_doc:
    method: aleph_emit
    handle:
      pass: store
  store:
    method: opensanctions.crawlers.eu_eeas_sanctions:store
aggregator:
  method: ftm_load_aleph
