name: gb_coh_disqualified
description: "[OSANC] Disqualified company directors from the UK (Companies House)"
schedule: never
pipeline:
  init:
    method: seed
    params:
      url: "https://beta.companieshouse.gov.uk/register-of-disqualifications/A"
    handle:
      pass: fetch_index
  fetch_index:
    method: fetch
    params:
      http_rate_limit: 5
    handle:
      pass: alphabetical
  alphabetical:
    method: opensanctions.crawlers.gb_coh_disqualified:alphabetical
    handle:
      pass: fetch_pages
  fetch_pages:
    method: fetch
    params:
      http_rate_limit: 5
    handle:
      pass: parse_pages
  parse_pages:
    method: opensanctions.crawlers.gb_coh_disqualified:pages
    params:
      http_rate_limit: 5
    handle:
      pass: officer
      url: fetch_pages
  officer:
    method: opensanctions.crawlers.gb_coh_disqualified:officer
aggregator:
  method: ftm_load_aleph
